package com.tourease.hotel.models.enums;

public enum FacilityEnum {
    WIFI,
    PARKING,
    SWIMMING_POOL,
    POOL,
    INSIDE_SWIMMING_POOL,
    GYM,
    FITNESS,
    SPA,
    ROOM_SERVICE,
    AIR_CONDITIONING,
    MINIBAR,
    CONFERENCE_ROOM,
    CHILDREN_PLAYGROUND,
    PET_FRIENDLY,
    PETS,
    BEACH_ACCESS,
    SHUTTLE_SERVICE,
    LAUNDRY,
    ELEVATOR,
    HOUR_FRONT_DESK,
    BREAKFAST,
    CHILD_BREAKFAST,
    LUNCH,
    CHILD_LUNCH,
    DINNER,
    CHILD_DINNER,
    IRON
}

