package com.tourease.hotel.models.enums;

public enum FacilityEnum {
    WIFI,
    PARKING,
    RESTAURANT,
    SWIMMING_POOL,
    INSIDE_SWIMMING_POOL,
    GYM,
    SPA,
    ROOM_SERVICE,
    AIR_CONDITIONING,
    BAR,
    BUSINESS_CENTER,
    CONCIERGE,
    CONFERENCE_ROOM,
    CHILDREN_PLAYGROUND,
    PET_FRIENDLY,
    BEACH_ACCESS,
    SHUTTLE_SERVICE,
    LAUNDRY,
    ELEVATOR,
    HOUR_FRONT_DESK;
}

